### ISSUE TITLE
Lumen Support?

### ISSUE THREAD

**Issue by JillzTom** [GetStream/stream-laravel#32]
It's not compatible with Lumen. Can you create a package for Lumen?

**Comment by tbarbugli** [comment]
added to our PHP support list. In the meantime you can use the PHP client directly.

**Comment by tugis** [comment]
As far as I have seen, the only reason why the package is not compatible with Lumen, is because of `configPath` method which is present in Laravel but not on Lumen.

As a workaround, what I did was creating my own `Application` class, extending `Lumen`one.

```
<?php

namespace App;

use Laravel\Lumen\Application as LumenApplication;

class Application extends LumenApplication
{
    /**
     * Get the configuration path.
     *
     * @return string
     */
    public function configPath()
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'config';
    }
}
```

of course then you need to edit your bootstrap/app.php file and use this new `Application` class. This way I'm able to use the package successfully on Lumen (create activities, retrieve streams, etc).

**Comment by linkthrow** [comment]
I've created a PR to allow lumen support

https://github.com/GetStream/stream-laravel/pull/63/files

**Comment by linkthrow** [comment]
This is now closed.

In bootstrap app do the following:

`
$app->register(\GetStream\StreamLaravel\StreamLumenServiceProvider::class);
$app->configure('stream-laravel');
`

Have to manually create stream-laravel.php in config

**Comment by hannesvdvreken** [comment]
@linkthrow would you mind creating a PR to add it to the readme?

**Comment by linkthrow** [comment]
Sure, will try tomorrow if I get time

**Comment by linkthrow** [comment]
https://github.com/GetStream/stream-laravel/pull/64#pullrequestreview-89391433

Here you go, feel free to change the version number, if you tag it

**Comment by hannesvdvreken** [comment]
upgrade to 2.3.0 should help
