### ISSUE TITLE
[QUESTION] Timeline feed is showing likes and comment activities.

### ISSUE THREAD

**Issue by imonoid** [GetStream/stream-laravel#50]
Hi guys,

Is there a way to get timeline feeds by activity?  My timeline seems to include following, likes, and comment activities.  I would like to make it work like the sample found in GetStream's homepage (the interactive demo), where homepage shows posts from followed users only and another page shows aggregated feed.  Should I filter it myself?  like:

if (activity verb == 'likes' or 'following' or 'comment') {
  //do nothing
} else {
 //add to display list
}

thanks.  nice project by the way.  God bless.

**Comment by dwightgunning** [comment]
Hi @imonoid, apologies for the missing your question here. Let's get you an answer!

As you correctly point out, a feed may contain Activities with various verbs. Filtering on the client is always an option and it's not directly supported in our API at this stage.

To elaborate further on the use-case you describe, it would be advisable to use separate Feed Groups to achieve what you describe.

The first two Feed Groups would relate to "posts" and you'd have two groups: 'user_posts' and 'posts_timeline' (following other users' 'user_posts' feeds) which the user will read in order to see the posts of all other users they follow.

In addition, two more Feed Groups would be used to for the other actions; 'likes', 'following', 'comment'.  Following a similar naming convention you'd have 'user_actions' and 'user_actions_timeline'.

Hopefully this answers the question!
PS. For general implementation questions, it's helpful to the developer community and responses come faster if you post on Stack Overflow using the tag 'getstream'. Just follow their guidelines and all will be well.
